"""bench - a benchmarking framework.

Every public symbol of the package is re-exported here, so user code (and the
examples) can stay on `from bench import ...` instead of reaching into
submodules. `__all__` is grouped by the module each symbol is defined in.
"""

from bench.__main__ import main
from bench.builder import (
    BenchAppBuilder,
    BenchmarkBuilder,
    BenchmarkGenerator,
    BuilderBase,
    Context,
    Data,
    Factory,
    MatrixAxis,
    NoBenchmarksMatchedError,
    ParamFactory,
    SubsuiteGenerator,
    SuiteBuilder,
    SuiteContext,
    SuiteGenerator,
    SuiteMaterializationError,
    UnresolvedCommand,
    bench,
    bench_app,
    default_filter,
    default_label,
    default_reporter,
    default_runner,
    default_success,
    from_files,
    plan,
    run,
    suite,
)
from bench.console.styling import Styling
from bench.core import stats
from bench.core.denoise import (
    DENOISE_DEFAULT_STATE_PATH,
    Denoise,
    is_root,
)
from bench.core.diagnostic import (
    Diagnostic,
    Severity,
    print_diagnostics,
    run_checks,
)
from bench.core.fingerprint import (
    BenchVersionProbe,
    CompositeProbe,
    Fingerprint,
    GitProbe,
    NoProbe,
    Probe,
    SystemProbe,
)
from bench.core.metric import (
    BuildableMetric,
    FloatPerLine,
    IterationMetric,
    Metric,
    MetricSource,
    RebenchMetric,
    RegexMetric,
    RUsage,
    StderrMetricSource,
    StdoutMetricSource,
    SystemTime,
    Time,
    UserTime,
    as_metric_source,
    max_rss,
)
from bench.core.outlier import (
    ModifiedZScore,
    NoDetection,
    OutlierDetection,
)
from bench.core.policy import (
    CoefficientOfVariation,
    FixedRuns,
    MaxDuration,
    PolicyState,
    StoppingPolicy,
)
from bench.core.process import (
    execute,
)
from bench.error import BenchError, print_exception
from bench.model.benchmark import (
    Benchmark,
    BenchmarkPred,
    LabelFn,
    Variant,
)
from bench.model.invocation import (
    Command,
    Env,
    Invocation,
    InvocationResult,
    SuccessFn,
    Timeout,
    Verdict,
)
from bench.model.results import (
    Direction,
    Execution,
    Iteration,
    Report,
    Sample,
    diagnostic_excerpt,
    report_from_json,
    report_to_json,
)
from bench.params import (
    REPORTER_GROUP,
    RUNNER_GROUP,
    SELECTION_GROUP,
    Params,
    ParamsGroup,
    SharedBenchParams,
    SharedReporterParams,
    SharedRunnerParams,
    SharedSelectionParams,
    add_params,
    build_params,
)
from bench.perf import (
    PerfRecord,
    PerfStat,
    PerfStatMetric,
)
from bench.report import (
    CompositeReporter,
    CsvReporter,
    DirReporter,
    JsonReporter,
    ProgressReporter,
    Reporter,
    execution_dir,
    variant_path,
)
from bench.runner import (
    Controller,
    DryRunner,
    ParallelRunner,
    Runner,
    SequentialRunner,
)
from bench.summary import (
    MEAN_HEADER_LONG,
    MEAN_HEADER_SHORT,
    MIN_MAX_HEADER,
    ByBenchmarkMetricSummary,
    ByMetricSummary,
    ComparisonSummary,
    CompositeSummary,
    DefaultSummary,
    GeomeanComparisonSummary,
    MetricFilterSummary,
    Summary,
    bench_label,
    counts_cell,
    format_by_benchmark_metric,
    format_by_metric,
    format_comparison,
    format_failures,
    mean_cells,
    mean_cells_raw,
    range_runs_cells,
    stat_line,
)

__all__ = [
    # bench.__main__
    "main",
    # bench.builder
    "ParamFactory",
    "SuiteGenerator",
    "NoBenchmarksMatchedError",
    "BenchAppBuilder",
    "run",
    "bench_app",
    "UnresolvedCommand",
    "Factory",
    "MatrixAxis",
    "BuilderBase",
    "BenchmarkBuilder",
    "bench",
    "from_files",
    "Data",
    "Context",
    "default_filter",
    "default_label",
    "default_runner",
    "default_success",
    "default_reporter",
    "SuiteContext",
    "BenchmarkGenerator",
    "SubsuiteGenerator",
    "SuiteBuilder",
    "suite",
    "SuiteMaterializationError",
    "plan",
    # bench.core.denoise
    "DENOISE_DEFAULT_STATE_PATH",
    "Denoise",
    "is_root",
    # bench.core.diagnostic
    "Severity",
    "Diagnostic",
    "run_checks",
    "print_diagnostics",
    # bench.core.fingerprint
    "Fingerprint",
    "Probe",
    "NoProbe",
    "CompositeProbe",
    "SystemProbe",
    "GitProbe",
    "BenchVersionProbe",
    # bench.core.metric
    "Time",
    "UserTime",
    "SystemTime",
    "RUsage",
    "max_rss",
    "RebenchMetric",
    "RegexMetric",
    "FloatPerLine",
    "Metric",
    "BuildableMetric",
    "MetricSource",
    "StdoutMetricSource",
    "StderrMetricSource",
    "as_metric_source",
    "IterationMetric",
    # bench.core.outlier
    "OutlierDetection",
    "NoDetection",
    "ModifiedZScore",
    # bench.core.policy
    "StoppingPolicy",
    "PolicyState",
    "FixedRuns",
    "CoefficientOfVariation",
    "MaxDuration",
    # bench.core.process
    "execute",
    # bench.error
    "BenchError",
    "print_exception",
    # bench.model.benchmark
    "LabelFn",
    "Benchmark",
    "BenchmarkPred",
    "Variant",
    # bench.model.invocation
    "Timeout",
    "Env",
    "Command",
    "Invocation",
    "InvocationResult",
    "Verdict",
    "SuccessFn",
    # bench.model.results
    "Direction",
    "Sample",
    "Iteration",
    "Execution",
    "Report",
    "diagnostic_excerpt",
    "report_to_json",
    "report_from_json",
    # bench.params
    "Params",
    "ParamsGroup",
    "SELECTION_GROUP",
    "SharedSelectionParams",
    "RUNNER_GROUP",
    "SharedRunnerParams",
    "REPORTER_GROUP",
    "SharedReporterParams",
    "SharedBenchParams",
    "add_params",
    "build_params",
    # bench.perf
    "PerfStatMetric",
    "PerfStat",
    "PerfRecord",
    # bench.report
    "Reporter",
    "CompositeReporter",
    "CsvReporter",
    "execution_dir",
    "variant_path",
    "DirReporter",
    "JsonReporter",
    "ProgressReporter",
    # bench.runner
    "Runner",
    "Controller",
    "DryRunner",
    "ParallelRunner",
    "SequentialRunner",
    # bench.console.styling
    "Styling",
    # bench.core.stats
    "stats",
    # bench.summary
    "Summary",
    "CompositeSummary",
    "MetricFilterSummary",
    "ByBenchmarkMetricSummary",
    "ComparisonSummary",
    "GeomeanComparisonSummary",
    "ByMetricSummary",
    "DefaultSummary",
    "bench_label",
    "stat_line",
    "MEAN_HEADER_LONG",
    "MEAN_HEADER_SHORT",
    "MIN_MAX_HEADER",
    "mean_cells",
    "mean_cells_raw",
    "counts_cell",
    "range_runs_cells",
    "format_by_benchmark_metric",
    "format_comparison",
    "format_by_metric",
    "format_failures",
]
